# Generated by Django 3.2.10 on 2024-09-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20240925_1629'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='deliverystaff',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='deliverystaff',
            name='username',
        ),
        migrations.AlterField(
            model_name='deliverystaff',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
