# Generated by Django 3.2.10 on 2024-09-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_auto_20240926_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='dropoff_location',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='pickup_location',
            field=models.JSONField(),
        ),
    ]
