# Generated by Django 3.2.10 on 2024-09-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_auto_20240926_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='blood_units',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
